// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;

/// @notice Deterministic `addValidator` fixture for the Monad staking precompile.
/// @dev Generated by scratch script mirroring staking-sdk-cli `add_validator`:
///      payload  = secpPub(33) ‖ blsPub(48) ‖ authAddress(20) ‖ amount(32 BE) ‖ commission(32 BE)
///      secpSig  = 64-byte r‖s over blake3(payload)
///      blsSig   = 96-byte G2 PoP-scheme signature over raw payload
///      Keys are throwaway: secp priv = 0x11..11, bls priv = 0x22..22. Never fund them.
library AddValidatorFixture {
    address internal constant AUTH_ADDRESS = address(0xA1);
    uint256 internal constant AMOUNT = 100000000000000000000000; // 100_000 MON
    uint256 internal constant COMMISSION = 100000000000000000; // 10%

    bytes internal constant SECP_PUBKEY = hex"034f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa";
    bytes internal constant BLS_PUBKEY =
        hex"8b5602ce59fb113eec6a6d917909b45e10560e69a4caa384d9006ab4fa1616c4883f89b4c731fcc932fac1b3b8bf82d6";

    bytes internal constant PAYLOAD =
        hex"034f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa8b5602ce59fb113eec6a6d917909b45e10560e69a4caa384d9006ab4fa1616c4883f89b4c731fcc932fac1b3b8bf82d600000000000000000000000000000000000000a100000000000000000000000000000000000000000000152d02c7e14af6800000000000000000000000000000000000000000000000000000016345785d8a0000";
    bytes internal constant SECP_SIG =
        hex"de825a9b28f9383770f41da8cf4f363311935844faea7f052c893dde7d97ae6b70b95f68174ba03c13ab5d12f73afa560f7cf4e52ad2c2f984e9e8e453d33168";
    bytes internal constant BLS_SIG =
        hex"b34871a747e131734b459a59645f3a201230dedc0f824b5e3aa28be0e14064ca9ddef134895f0a95234536958d2d4d2200a2388c11fe97f3c891e1e1ea5943af2537a10673d7016e88ce450e08e73b629b14b251d3ead85c8e07122487f5598c";
}
